# Generated by Django 5.1.7 on 2025-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('locker_number', models.PositiveIntegerField(unique=True)),
                ('locker_combination', models.CharField(max_length=10)),
                ('good_student', models.BooleanField(default=True)),
            ],
        ),
    ]
